project/models/user.py
import datetime
import re

from marshmallow import fields, validates, ValidationError

from .. import db
from .. import ma
from .. import bcrypt
from ..helpers.mixins import ModelMixin

class User(ModelMixin, db.Model):

    __tablename__ = 'users'

    user_id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(200), unique=True, nullable=False)
    name = db.Column(db.String(50), nullable=False)
    password = db.Column(db.String(200), nullable=False)
    confirmed = db.Column(db.Boolean, nullable=False, default=False)
    created_at = db.Column(db.DateTime, default=datetime.datetime.utcnow, nullable = False)

    def __init__(self, email, name, password, confirmed=False):
        self.email = email
        self.name = name
        self.password = bcrypt.generate_password_hash(password)
        self.confirmed = confirmed

    def __repr__(self):
        return '<User: {0}>'.format(self.name)
        
    @property
    def is_authenticated(self):
        return True

    @property
    def is_active(self):
        return self.confirmed

    @property
    def is_anonymous(self):
        return False

    def get_id(self):
        return self.user_id

class UserSchema(ma.ModelSchema):
    password = fields.String(required=True)
    email = fields.Email(required=True)
    class Meta:
        model = User
        load_only = ["password",]

    @validates('email')
    def validate_email(self, value):
        if User.query.filter(User.email == value).first():
            raise ValidationError("User already exists.")

    @validates('password')
    def validate_password(self, value):
        if not(re.match(r'(?=.*[A-Z])(?=.*[0-9])(?=.*[a-z]).{8,}', value)):
            raise ValidationError("Password not compliant.")

project/users/forms.py
#  project/users/forms.py

from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField
from wtforms.validators import DataRequired, Length, EqualTo, Email, Regexp, ValidationError

from ..models.user import User

class RegisterForm(FlaskForm):
    name = StringField('Name', validators = [DataRequired(), Length(min = 3, max = 25)])
    email = StringField('Email', validators = [DataRequired(), Email(), Length(min = 6, max = 40)])
    password = PasswordField('Password', validators = [DataRequired(), Regexp('(?=.*[A-Z])(?=.*[0-9])(?=.*[a-z]).{8,}', message='Password not compliant.')])
    confirm = PasswordField('Repeat Password', validators = [DataRequired(), EqualTo('password', message='Passwords must match.')])

    def validate_email(self, field):
        user = User.query.filter(User.email==field.data).first()
        if user is not None:
            raise ValidationError("User already registered.")
        return True

class LoginForm(FlaskForm):
    email = StringField('Email', validators = [DataRequired()])
    password = PasswordField('Password', validators = [DataRequired()])

project/users/auth.py
from .. import db, email, bcrypt
from ..models.user import User, UserSchema

def authenticate(username, password):
    user = User.query.filter_by(email=username).first()
    if user and user.confirmed and bcrypt.check_password_hash(user.password, password):
        return user

def identity(payload):
    user_id = payload['identity']
    return User.query.filter_by(user_id=user_id).first()

project/users/views.py
# project/users/views.py
import datetime
from flask import Blueprint, make_response, jsonify, request, abort, render_template, redirect, url_for, session, flash
from flask_login import login_user, logout_user, login_required, current_user

from .. import db, email, bcrypt
from ..models.user import User, UserSchema
from ..token import generate_confirmation_token, confirm_token
from .forms import RegisterForm, LoginForm

# Config
user_blueprint = Blueprint('users', __name__)

@user_blueprint.route('/register', methods=['GET', 'POST'])
def user_register():
    error = None
    form = RegisterForm(request.form)
    if request.method == 'POST':
        if form.validate_on_submit():
            new_user = User.save({"name":form.name.data, "email":form.email.data, "password":form.password.data}, UserSchema)
            _send_confirmation_email(new_user)
            flash('You are successful registered. Click on the link we send you to your email to confirm your address', 'success')
            return redirect(url_for('users.user_login'))
    return render_template('users/register.html', form=form, error=error)

@user_blueprint.route('/login', methods=['GET', 'POST'])
def user_login():
    error = None
    form = LoginForm(request.form)
    if request.method == 'POST':
        if form.validate_on_submit():
            user = User.query.filter_by(email = form.email.data).first()
            if user is not None and bcrypt.check_password_hash(user.password, form.password.data):
                login_user(user)
                return redirect(url_for('users.home'))
            flash('Invalid credentials.', 'danger')
    return render_template('users/login.html', form=form, error=error)

@user_blueprint.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('users.user_login'))

@user_blueprint.route('/confirm/<token>', methods=['GET'])
def user_confirm(token):
    email = confirm_token(token)
    if (email):
        user = User.query.filter_by(email=email).first_or_404()
        if user.confirmed:
            flash('Account already confirmed. Please login.', 'success')
        else:
            flash('Congratulations, your account is now active. You can login.', 'success')
            user.update({"confirmed":True})
    else:
        token_expired(token)
    return redirect(url_for('users.user_login'))

def token_expired(token):
    email = confirm_token(token, None)
    user = User.query.filter_by(email=email).first_or_404()
    _send_confirmation_email(user)
    flash('The confirmation link is invalid or has expired. A new one has been sent to your email.', 'danger')
    return redirect(url_for('users.user_login'))

@user_blueprint.route('/', methods=['GET'])
@login_required
def home():
    return "Welcome " + current_user.email

def _send_confirmation_email(user):
    token = generate_confirmation_token(user.email)
    confirm_url = url_for('users.user_confirm', token=token, _external=True)
    expiration_date = '{:%d-%m-%Y %H:%M}'.format(datetime.datetime.utcnow() + datetime.timedelta(hours=1))
    html = render_template('users/email/confirm.html', confirm_url=confirm_url, user=user, expiration_date=expiration_date)
    subject = "Welcome to MyExpense, please confirm your email."
    email.AsyncEmail(user.email, subject, html).start()

project/templates/users/login.html
{% extends "./_base.html" %}
{% block content %}

<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <div class="panel panel-default">
            <div class="panel-body">
                <form action="" method="POST" class="form-horizontal">
                    {{ form.csrf_token }}
                    <div class="form-group {{ 'has-error' if form.email.errors }}">
                        {{ form.email.label(class_="col-md-4 control-label") }}
                        <div class="col-md-6">
                            {{ form.email(class_="form-control") }}
                            {% if form.email.errors %}
                            <span class="text-danger">
                                {% for error in form.email.errors %}
                                    {{ error }}
                                {% endfor %}
                            </span>
                            {% endif %}
                        </div>
                    </div>
                    <div class="form-group {{ 'has-error' if form.password.errors }}">
                        {{ form.password.label(class_="col-md-4 control-label") }}
                        <div class="col-md-6">
                            {{ form.password(class_="form-control") }}
                            {% if form.password.errors %}
                            <span class="text-danger">
                                {% for error in form.password.errors %}
                                    {{ error }}
                                {% endfor %}
                            </span>
                            {% endif %}
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-6 col-md-offset-4">
                            <button class="btn btn-primary" type="submit">Login</button>
                        </div>
                    </div>
                </form>
                <div>
                    <p><em>Not registered?</em> Click <a href="{{ url_for('users.user_register') }}">here</a> to register.</p>
                </div>
            </div>
        </div>
    </div>   
</div>
{% endblock %}

project/templates/users/register.html
{% extends "./_base.html" %}
{% block content %}

<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <div class="panel panel-default">
            <div class="panel-body">
                <form action="" method="POST" class="form-horizontal">
                    {{ form.csrf_token }}
                    <div class="form-group {{ 'has-error' if form.name.errors }}">
                        {{ form.name.label(class_="col-md-4 control-label") }}
                        <div class="col-md-6">
                            {{ form.name(class_="form-control") }}
                            {% if form.name.errors %}
                            <span class="text-danger">
                                {% for error in form.name.errors %}
                                    {{ error }}
                                {% endfor %}
                            </span>
                            {% endif %}
                        </div>
                    </div>
                    <div class="form-group {{ 'has-error' if form.email.errors }}">
                        {{ form.email.label(class_="col-md-4 control-label") }}
                        <div class="col-md-6">
                            {{ form.email(class_="form-control") }}
                            {% if form.email.errors %}
                            <span class="text-danger">
                                {% for error in form.email.errors %}
                                    {{ error }}
                                {% endfor %}
                            </span>
                            {% endif %}
                        </div>
                    </div>
                    <div class="form-group {{ 'has-error' if form.password.errors }}">
                        {{ form.password.label(class_="col-md-4 control-label") }}
                        <div class="col-md-6">
                            {{ form.password(class_="form-control") }}
                            {% if form.password.errors %}
                            <span class="text-danger">
                                {% for error in form.password.errors %}
                                    {{ error }}
                                {% endfor %}
                            </span>
                            {% endif %}
                        </div>
                    </div>
                    <div class="form-group {{ 'has-error' if form.confirm.errors }}">
                        {{ form.confirm.label(class_="col-md-4 control-label") }}
                        <div class="col-md-6">
                            {{ form.confirm(class_="form-control") }}
                            {% if form.confirm.errors %}
                            <span class="text-danger">
                                {% for error in form.confirm.errors %}
                                    {{ error }}
                                {% endfor %}
                            </span>
                            {% endif %}
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-6 col-md-offset-4">
                            <button class="btn btn-primary" type="submit">Register</button>
                        </div>
                    </div>
                </form>
                <div>
                    <p><em>Already registered?</em> Click <a href="{{ url_for('users.user_login') }}">here</a> to login.</p>
                </div>
            </div>
        </div>
    </div>   
</div>
{% endblock %}